package com.wang.weather;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-06-09T20:43:35.888+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://weather.wang.com/", name = "WeatherInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface WeatherInterface {

    @WebMethod
    @RequestWrapper(localName = "queryWeather", targetNamespace = "http://weather.wang.com/", className = "com.wang.weather.QueryWeather")
    @ResponseWrapper(localName = "queryWeatherResponse", targetNamespace = "http://weather.wang.com/", className = "com.wang.weather.QueryWeatherResponse")
    @WebResult(name = "result", targetNamespace = "")
    public java.util.List<com.wang.weather.WeatherModel> queryWeather(
        @WebParam(name = "cityName", targetNamespace = "")
        java.lang.String cityName
    );
}
