
package com.wang.ws.area.server.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AreaServiceInterfaceImpl", targetNamespace = "http://service.server.area.ws.wang.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AreaServiceInterfaceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryArea", targetNamespace = "http://service.server.area.ws.wang.com/", className = "com.wang.ws.area.server.service.QueryArea")
    @ResponseWrapper(localName = "queryAreaResponse", targetNamespace = "http://service.server.area.ws.wang.com/", className = "com.wang.ws.area.server.service.QueryAreaResponse")
    @Action(input = "http://service.server.area.ws.wang.com/AreaServiceInterfaceImpl/queryAreaRequest", output = "http://service.server.area.ws.wang.com/AreaServiceInterfaceImpl/queryAreaResponse")
    public String queryArea(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
